Repository kubernetes/gengo, pull requests merged in 2018-02, with the labels that each got.

#94 Output 'Code generated by' comment if arg is set
  args/args.go
  examples/deepcopy-gen/generators/deepcopy.go
  examples/deepcopy-gen/output_tests/builtins/zz_generated.go
  examples/deepcopy-gen/output_tests/interfaces/zz_generated.go
  examples/deepcopy-gen/output_tests/maps/zz_generated.go
  examples/deepcopy-gen/output_tests/pointer/zz_generated.go
  examples/deepcopy-gen/output_tests/slices/zz_generated.go
  examples/deepcopy-gen/output_tests/structs/zz_generated.go
  examples/deepcopy-gen/output_tests/wholepkg/zz_generated.go
  examples/defaulter-gen/_output_tests/empty/zz_generated.go
  examples/defaulter-gen/_output_tests/pointer/zz_generated.go
  examples/defaulter-gen/_output_tests/slices/zz_generated.go
  examples/defaulter-gen/_output_tests/wholepkg/zz_generated.go
  examples/defaulter-gen/generators/defaulter.go
  examples/set-gen/generators/sets.go
  examples/set-gen/sets/byte.go
  examples/set-gen/sets/doc.go
  examples/set-gen/sets/empty.go
  examples/set-gen/sets/int.go
  examples/set-gen/sets/int64.go
  examples/set-gen/sets/string.go
Labels: cncf-cla: yes, lgtm, size/M

#73 deepcopy: add alias support
  examples/deepcopy-gen/generators/deepcopy.go
  examples/deepcopy-gen/generators/deepcopy_test.go
  examples/deepcopy-gen/output_tests/aliases/doc.go
  examples/deepcopy-gen/output_tests/aliases/zz_generated.go
  examples/deepcopy-gen/output_tests/wholepkg/zz_generated.go
Labels: cncf-cla: yes, lgtm, size/XXL

#102 Fix travis, ignore vendored Makefiles
  .travis.yml
  examples/deepcopy-gen/output_tests/aliases/zz_generated.go
Labels: cncf-cla: yes

#98 Add myself to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
