Repository kubernetes/gengo, pull requests merged in 2020-11, with the labels that each got.

#190 Preallocate set to the length of the passed elements
  examples/set-gen/generators/sets.go
  examples/set-gen/sets/byte.go
  examples/set-gen/sets/int.go
  examples/set-gen/sets/int64.go
  examples/set-gen/sets/string.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#191 AddingPowerSupport&CI
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#188 Capture the values of constant declarations.
  parser/parse.go
  parser/parse_test.go
  types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#192 Update defaulter-gen to support +default annotation
  examples/defaulter-gen/Makefile
  examples/defaulter-gen/_output_tests/marker/defaults.go
  examples/defaulter-gen/_output_tests/marker/doc.go
  examples/defaulter-gen/_output_tests/marker/fake_deepcopy_conversion.go
  examples/defaulter-gen/_output_tests/marker/marker_test.go
  examples/defaulter-gen/_output_tests/marker/type.go
  examples/defaulter-gen/_output_tests/marker/zz_generated.go
  examples/defaulter-gen/generators/defaulter.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL
