Repository kubernetes/gengo, pull requests merged in 2020-01, with the labels that each got.

#160 Use UTC for calculation of year
  args/args.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#161 Use YAML format for import-restrictions
  .import-restrictions
  examples/import-boss/generators/import_restrict.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#162 Update plural_namer.go
  namer/plural_namer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#163 Add interface method comment lines
  parser/parse.go
  parser/parse_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
