Repository kubernetes/gengo, pull requests merged in 2020-04, with the labels that each got.

#173 Switch to klog v2
  .travis.yml
  examples/deepcopy-gen/generators/deepcopy.go
  examples/deepcopy-gen/main.go
  examples/defaulter-gen/generators/defaulter.go
  examples/defaulter-gen/main.go
  examples/import-boss/generators/import_restrict.go
  examples/import-boss/main.go
  examples/set-gen/generators/sets.go
  examples/set-gen/generators/tags.go
  examples/set-gen/main.go
  generator/execute.go
  generator/import_tracker.go
  parser/parse.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#167 Convert path to slashes before passing to build.Context.Import()
  parser/parse.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#175 fix method with same sigature comments mismatch
  parser/parse.go
  parser/parse_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
