Repository kubernetes/gengo, pull requests merged in 2024-01, with the labels that each got.

#258 Update OWNERS for gengo
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#251 Defaults: Don't look at JSON omitempty
  examples/defaulter-gen/_output_tests/marker/fake_deepcopy_conversion.go
  examples/defaulter-gen/_output_tests/marker/type.go
  examples/defaulter-gen/_output_tests/marker/zz_generated.go
  examples/defaulter-gen/generators/defaulter.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#243 chore: use sort.Strings(...) instead of sort.Sort(sort.StringSlice(...))
  examples/import-boss/generators/import_restrict.go
  namer/import_tracker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#244 Normalize generator name in comment between Windows and Linux/Unix
  args/args.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#254 Stop using sets-gen in deepcopy-gen
  examples/deepcopy-gen/generators/deepcopy.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
