Repository kubernetes/gengo, pull requests merged in 2024-09, with the labels that each got.

#277 Performance: Use FormatOnly on imports
  v2/generator/execute.go
  v2/generator/import_tracker.go
  v2/generator/import_tracker_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#278 Ensure "make verify" verifies v2
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#281 Preserve existing behavior with go1.22/1.23 alias type parsing
  v2/Makefile
  v2/examples/kilroy/testdata/simple/file.go
  v2/examples/kilroy/testdata/simple/generated.kilroy.go
  v2/examples/pointuh/testdata/results/simple/generated.pointuh.go
  v2/examples/pointuh/testdata/simple/file.go
  v2/examples/tracer/testdata/simple/file.go
  v2/examples/tracer/testdata/simple/out.txt
  v2/parser/parse.go
  v2/parser/parse_122.go
  v2/parser/parse_pre_122.go
Labels: cncf-cla: yes, lgtm, size/L, approved
