Repository kubernetes/gengo, pull requests merged in 2025-02, with the labels that each got.

#287 Add SnippetWriter.Merge() to carry error state
  v2/generator/snippet_writer.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#289 Add types.Any and types.Pointer
  v2/types/types.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#282 fix: Correct CONTRIBUTING.md link
  v2/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#290 Add Type.IsComparable()
  v2/parser/parse.go
  v2/parser/parse_test.go
  v2/types/types.go
Labels: cncf-cla: yes, lgtm, size/M, approved
